language: python
env:
  global:
  # Set defaults to avoid repeating in most cases
  - PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
  - NUMPY_VERSION=stable
  - MAIN_CMD='python setup.py'
  - CONDA_DEPENDENCIES='sphinx cartopy scipy numpy coveralls coverage codecov behave mock pycoast pydecorate six appdirs pykdtree pyresample docutils pyyaml matplotlib'
  - PIP_DEPENDENCIES=''
  - SETUP_XVFB=False
  - EVENT_TYPE='push pull_request cron'
  - SETUP_CMD='test'
  - CONDA_CHANNELS='conda-forge'
  - CONDA_CHANNEL_PRIORITY='True'
matrix:
  include:
    - env: PYTHON_VERSION=2.7
      os: linux
    - env: PYTHON_VERSION=2.7
      os: osx
      language: generic
    - env: PYTHON_VERSION=3.6
      os: linux
    - env: PYTHON_VERSION=3.6
      os: osx
      language: generic
install:
    - git clone --depth 1 git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    # reactivate environment to set proj environment variables
    - conda deactivate
    - conda activate test
script: coverage run --source=trollsched setup.py test
after_success:
- if [[ $PYTHON_VERSION == 3.6 ]]; then coveralls; fi
#
deploy:
  - provider: pypi
    user: adybbroe
    password:
      secure: SY0qo7sZXDjDx0DHvuXrHvL9VTAulgU/T33d6UWXf469jT9DOexuZ2VYLgJbYQen5FSe5JmQE0ZMdId1cb8IPP/77qCgQK6f0lRDa43fSYXhcD+fHzlQskievJrwamkRYx6WBrJbwGAKBNinUgNSaTdbh9XUugziGFiOHUfVppM=
    distributions: sdist bdist_wheel
    skip_existing: true
    on:
      tags: true
      repo: pytroll/pytroll-schedule
notifications:
  slack:
    rooms:
    - pytroll:96mNSYSI1dBjGyzVXkBT6qFt#pytroll-schedule
